// <auto-generated />
using APIFutebol.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIFutebol.Migrations
{
    [DbContext(typeof(FutebolContext))]
    [Migration("20220819201424_Create Initial")]
    partial class CreateInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("APIFutebol.Models.Arbitragem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NomeBandeira1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeBandeira2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeJuiz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Arbitragens");
                });

            modelBuilder.Entity("APIFutebol.Models.Confronto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArbitragemId")
                        .HasColumnType("int");

                    b.Property<string>("Campeonato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChutesAGol_Time1")
                        .HasColumnType("int");

                    b.Property<int>("ChutesAGol_Time2")
                        .HasColumnType("int");

                    b.Property<string>("Estadio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocalizacaoId")
                        .HasColumnType("int");

                    b.Property<int>("PublicoPresente")
                        .HasColumnType("int");

                    b.Property<int>("ResultadoId")
                        .HasColumnType("int");

                    b.Property<string>("Times")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArbitragemId");

                    b.HasIndex("LocalizacaoId");

                    b.HasIndex("ResultadoId")
                        .IsUnique();

                    b.ToTable("Confrontos");
                });

            modelBuilder.Entity("APIFutebol.Models.Localizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PaisEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisTime1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisTime2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Localizacoes");
                });

            modelBuilder.Entity("APIFutebol.Models.Resultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Artilharia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("APIFutebol.Models.Confronto", b =>
                {
                    b.HasOne("APIFutebol.Models.Arbitragem", "Arbitragem")
                        .WithMany("Confrontos")
                        .HasForeignKey("ArbitragemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIFutebol.Models.Localizacao", "Localizacao")
                        .WithMany("Confrontos")
                        .HasForeignKey("LocalizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIFutebol.Models.Resultado", "Resultado")
                        .WithOne("Confronto")
                        .HasForeignKey("APIFutebol.Models.Confronto", "ResultadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arbitragem");

                    b.Navigation("Localizacao");

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("APIFutebol.Models.Arbitragem", b =>
                {
                    b.Navigation("Confrontos");
                });

            modelBuilder.Entity("APIFutebol.Models.Localizacao", b =>
                {
                    b.Navigation("Confrontos");
                });

            modelBuilder.Entity("APIFutebol.Models.Resultado", b =>
                {
                    b.Navigation("Confronto")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
